### ISSUE TITLE
Questions about the Technical apendix

### ISSUE THREAD

**Issue by fh1469** [nicholashestand/Active_Portfolio_Management#2]
Hi Nicholas,

Hope you are doing well. I wanted to know whether you were able to understand and do the calculations of the technical appendix and their exercises. If so,  i would like to get some advice. I'm having a hard time trying to understand. I have a deep knowledge of factor models since I work at a portfolio management firm so I can share my knowledge on that. 

Thanks

Francis

**Comment by nchlswllms** [comment]
Hi Francis,

I have added solutions to the technical appendix of Chapter 2, which you can find in my fork of the repository.

Best,

Nick
